# Generated by Django 5.1.5 on 2025-04-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='mastodon_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
    ]
